import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import { z } from 'zod'

import { fail, ok, type Result } from '../core/result.js'
import { newSealPair } from '../core/sealing.js'
import { resolveSink, sinkKeyNames, writeToSink, type ResolvedSink } from '../core/sinks.js'
import { ENCODINGS } from '../core/generated.js'
import type { RequestedSecret, RequestStore, SecretRequest } from '../core/store.js'
import { keptNames, valuesToWrite } from '../core/values.js'
import { numbered } from '../core/wording.js'
import { askerFor } from '../registry/clients.js'
import { formatIds } from '../registry/formats.js'
import { providerRefs } from '../registry/registry.js'
import type { LoopbackServer } from '../web/server.js'
import { unreported, type IdleReport } from './idle.js'
import type { Presentation, Presenter } from './present.js'
import type { Whereabouts } from './remote.js'
import { requestedSecrets } from './requested.js'

const AWAIT_TIMEOUT_MS = 60_000

const WAIT_SLACK_MS = 2_000

const COLLECT_DESCRIPTION = `Get the values a task needs — API keys, tokens, connection strings, settings — written
where the project reads them, typed by the human or generated by offprompt. Call this instead of asking the user to paste
a secret into the conversation.

Each entry in \`secrets\` is one key, and says how its value comes to be:
- \`generate: {}\` — a random value, 32 bytes of base64url unless set, made on the user's page (or by offprompt when no
  page opens); the user may paste one they already use instead. You never see it. For AUTH_SECRET, JWT_SECRET,
  SESSION_SECRET and encryption keys. A key that is already set is kept as it is.
- \`provider\` — a key the human gets from a provider, such as \`provider: "stripe"\` for STRIPE_SECRET_KEY. The page
  shows the provider's logo and links to where the key is made.
- \`format\` — a value of a known kind that no one provider issues, such as \`format: "postgres_url"\` for DATABASE_URL.
  The page links to providers where the human can create one.
- none of these — any other value, taken as plain text. A provider's key is still recognised by its usual name.
Set \`secret: false\` on a value that is not secret, such as MAX_RETRIES, and the page shows it in the clear.

When every key is generated, nothing opens: offprompt writes them and returns. Otherwise it opens a page in the user's
browser and this call waits there, for up to five minutes, while the human types. It returns once the values have been
written or the request has expired, so there is nothing to poll and nothing to do in the meantime.

In a cloud sandbox or a remote VM, a browser opened there is one the user cannot see. Set \`sandbox: true\` only when your
environment tells you that is where you run, as your instructions or the platform you run on do. A temporary folder, or a
run with nobody at the terminal, is not a sign of one, and offprompt detects the common environments itself. The call then
returns at once with a link: show it to the user in your reply, then call await_secret.
The user types in their own browser, and the values are encrypted there so that only the sandbox can read them.

You never receive a value. You get back the key names and the file they landed in, and you reference them by name from
then on, for example process.env.RESEND_API_KEY. Never open, cat, grep or print that file afterwards: reading it puts
the values into the transcript, which is the one thing this tool exists to prevent. The result lists every key the
file holds, so there is nothing left to check.

A written result opens with \`tell_user\`: "Fingerprint" and four emoji the user's page shows too. Write that line to
the user as soon as the call returns, before your next tool call, on a line of its own, for every write, one that comes
straight after another included. The user compares the two while the page is still open, so this does not wait for the
end of your task or for your next call to offprompt.

When the result carries a \`url\`, the human has to open it and nothing can happen until they do. Put the link in your
reply to them, on its own line, where they will see it. A link mentioned only in your reasoning, or buried in a
paragraph, is a request the human never receives.

State the intent once: \`reason\` is shown to the human as your claim about why the values are needed, so write it for
them, not for yourself.`

const AWAIT_DESCRIPTION = `Wait for a collect_secret request that came back still "awaiting" — which happens when
offprompt runs in a cloud sandbox, or had no browser to open and handed you the page URL to pass on. Long-polls for up to 60 seconds and returns
"written", "awaiting" or "expired". Call it again while the status is "awaiting".`

const CANCEL_DESCRIPTION = `Close a collect_secret request that is no longer needed. Anything already typed on the
page is discarded.`

const sinkSchema = z.discriminatedUnion('kind', [
  z.object({
    kind: z.literal('dotenv'),
    path: z.string().default('.env').describe('Path to the dotenv file, relative to the project root.'),
  }),
  z.object({
    kind: z.literal('file'),
    path: z.string().describe('Path to the file, relative to the project root. The value becomes its whole content.'),
  }),
])

const generateSchema = z.object({
  bytes: z.number().int().min(16).max(64).default(32).describe('Random bytes before encoding.'),
  encoding: z.enum(ENCODINGS).default('base64url').describe('How the bytes are written: base64url, base64 or hex.'),
})

const secretSchema = z.object({
  name: z
    .string()
    .regex(/^[A-Z][A-Z0-9_]*$/, 'name must be SCREAMING_SNAKE_CASE, for example RESEND_API_KEY')
    .max(128)
    .describe('The env key the value is stored under. Also the label the human sees.'),
  generate: generateSchema
    .optional()
    .describe(
      'A random value, made on the page (or by offprompt when no page opens); the user may paste their own. You never see it. For signing and encryption secrets. A key that is already set is kept.',
    ),
  provider: z
    .enum(providerRefs)
    .optional()
    .describe(
      'A key the human gets from this provider. Give provider/credential, such as stripe/webhook_secret, when the provider issues several keys and the name does not say which.',
    ),
  format: z
    .enum(formatIds)
    .optional()
    .describe('What the value is, when no one provider issues it, such as postgres_url for DATABASE_URL.'),
  secret: z
    .boolean()
    .optional()
    .describe('false for a value that is not secret, such as MAX_RETRIES or a publishable key. It is shown in the clear.'),
  caption: z
    .string()
    .min(1)
    .max(90)
    .optional()
    .describe(
      'One short line shown under the field, such as where to find the value: "Stripe dashboard → Developers → API keys". Keep it brief.',
    ),
})

const collectInput = {
  secrets: z
    .array(secretSchema)
    .min(1)
    .max(12)
    .describe(
      'Every key you need, in one request. The human fills them on one page and can paste them all at once.',
    ),
  reason: z
    .string()
    .min(1)
    .max(2000)
    .describe(
      'Why the values are needed, written for the human and shown on the page as your claim. Markdown is rendered: bold, italics, code, lists, quotes. Links show their address as text and are not clickable.',
    ),
  sink: sinkSchema.describe('Where the values are written. Fixed now and not re-read from the page.'),
  sandbox: z
    .boolean()
    .optional()
    .describe(
      'true only when your environment tells you that you run in a cloud sandbox, a container or a remote VM, where a browser would open on a screen the user cannot see. Not a temporary folder or a run nobody watches. offprompt detects the common environments itself, and on the user\'s own Mac or Windows machine it opens the page there either way.',
    ),
}

const awaitInput = {
  request_id: z.string().min(1).describe('The request_id returned by collect_secret.'),
}

const sinkOutput = z.object({ kind: z.string(), path: z.string() })

const statusOutput = {
  tell_user: z
    .string()
    .optional()
    .describe(
      'The line to write to the user as soon as the call returns, before your next tool call: "Fingerprint" and the four emoji their page shows.',
    ),
  request_id: z.string(),
  status: z.enum(['awaiting', 'written', 'expired']),
  names: z.array(z.string()),
  kept: z.array(z.string()).optional(),
  emoji: z
    .string()
    .optional()
    .describe(
      "A fingerprint of the values as the file holds them. The user's page shows the four it took from what they typed. Write them to the user as soon as the call returns, before your next tool call.",
    ),
  file_keys: z
    .array(z.string())
    .optional()
    .describe('Every key the file holds after the write, names only, so the file never needs opening.'),
  sink: sinkOutput,
  note: z.string(),
}

const collectOutput = {
  ...statusOutput,
  expires_in: z.number(),
  url: z.string().optional(),
}

const sinkReport = (request: SecretRequest) => ({
  kind: request.sink.kind,
  path: request.sink.relativePath,
})

const namesOf = (request: SecretRequest) => request.secrets.map(secret => secret.name)

const listed = (names: readonly string[]) => names.join(', ')

/** Generated keys the write left alone, reported only when there are any. */
const keptReport = (request: SecretRequest) => {
  const kept = request.status === 'written' ? keptNames(request.secrets) : []
  return kept.length === 0 ? {} : { kept }
}

/**
 * One payload on both channels. A client that reads `structuredContent` and one that
 * reads the text block have to see the same thing, or guidance that only lives in the
 * text — the fallback URL among it — is silently dropped. A written result opens with a
 * line that says part of the same in words, for the person: see `headline`.
 */
const bothWays = <T>({ payload, lead }: { payload: T; lead?: string | undefined }) => ({
  content: [
    ...(lead === undefined ? [] : [{ type: 'text' as const, text: lead }]),
    { type: 'text' as const, text: JSON.stringify(payload, null, 2) },
  ],
  structuredContent: payload,
})

/**
 * What a write did, in one line for the person rather than the model, as the Written page
 * pictures it: "Wrote 2 values to .env · fingerprint 🍋 🥝 🌮 🧀". It is for hosts that show a
 * result's text under the call, such as Codex and Pi; Claude Code shows the structured result
 * instead, which opens with `tell_user` for the same reason.
 */
const headline = (request: SecretRequest) => {
  if (request.status !== 'written') return undefined
  const kept = keptNames(request.secrets)
  const written = request.secrets.length - kept.length
  const path = request.sink.relativePath
  const wrote = written === 0 ? `${path} already held ${listed(kept)}` : `Wrote ${numbered(written, 'value')} to ${path}`
  return request.emoji === undefined ? wrote : `${wrote} · fingerprint ${request.emoji}`
}

/**
 * What the agent does after a write. The fingerprint comes first and is asked for at once:
 * asked for at the end of the reply, it arrived after the rest of a long task, when the page
 * was long closed, or not at all.
 */
const writtenNote = ({ request, fileKeys }: { request: SecretRequest; fileKeys: readonly string[] }) => {
  const kept = keptNames(request.secrets)
  const names = namesOf(request)
  const many = names.length > 1
  const path = request.sink.relativePath
  const fingerprint =
    request.emoji === undefined
      ? []
      : [
          `Write this to the user now, before your next tool call, on a line of its own: "Fingerprint ${request.emoji}".`,
          'They are matching it against the four on their page while it is still open, so it cannot wait for the end of your task or for your next call to offprompt, and a fingerprint only in your reasoning never reaches them.',
        ]
  const keptLine =
    kept.length === 0
      ? []
      : [`${listed(kept)} ${kept.length > 1 ? 'were' : 'was'} already set and left as ${kept.length > 1 ? 'they were' : 'it was'}.`]
  const holds = fileKeys.length === 0 ? [] : [`The file now holds ${listed(fileKeys)}.`]
  return [
    ...fingerprint,
    request.sink.kind === 'file'
      ? `${listed(names)} is the whole of ${path}. Have the project read it from that path.`
      : `${listed(names)} ${many ? 'are' : 'is'} in ${path}. Read ${many ? 'them' : 'it'} from the environment by name.`,
    ...keptLine,
    ...holds,
    `Do not open, cat, grep or print ${path}: reading it puts the values into the transcript. Nothing needs checking; the write was atomic and every value passed its checks.`,
  ].join(' ')
}

const statusNote = ({ request, fileKeys }: { request: SecretRequest; fileKeys: readonly string[] }) => {
  if (request.status === 'written') return writtenNote({ request, fileKeys })
  if (request.status === 'expired')
    return `${listed(namesOf(request))} was not collected. Call collect_secret again if still needed.`
  return `Still waiting for the human. Call await_secret again with this request_id.`
}

/** The human must see the link: a link only in the agent's reasoning is a request that never arrives. */
const SHOW_LINK =
  'Show the user this link in your reply, on its own line, and tell them to open it and type the values there. Nothing happens until they do:'

const remoteNote = (presentation: Extract<Presentation, { channel: 'remote' }>) => {
  const { url, via, shownByHost } = presentation
  const port = String(presentation.port)
  if (via === 'loopback') {
    return `offprompt could not open a tunnel from this sandbox. ${SHOW_LINK} ${url} It opens only if their tool forwards port ${port} to their machine; if it forwards to another port, they change the port in the link. If nothing forwards it, this sandbox cannot expose a page: they can turn on port forwarding or allow outbound connections to Cloudflare, then ask you to try again. Then call await_secret.`
  }
  const exposed = 'offprompt is running in a cloud sandbox and exposed its page through a tunnel.'
  if (shownByHost) return `${exposed} The host is showing the user the link. Call await_secret.`
  return `${exposed} ${SHOW_LINK} ${url} Say nothing else about it. Then call await_secret.`
}

const noteFor = (presentation: Presentation) => {
  if (presentation.channel === 'remote') return remoteNote(presentation)
  if (presentation.channel === 'result') {
    return `offprompt could not open the page itself: ${presentation.reason}. ${SHOW_LINK} ${presentation.url} Say nothing else about it. Then call await_secret.`
  }
  return "An offprompt page is open in the user's browser. Do not paste or repeat any URL for it."
}

/** Registers `collect_secret`, `await_secret` and `cancel_secret`. */
export const registerTools = ({
  server,
  store,
  loopback,
  present,
  project,
  where = 'unsure',
  clientInfo = () => server.server.getClientVersion(),
  during = unreported,
}: {
  server: McpServer
  store: RequestStore
  loopback: LoopbackServer
  present: Presenter
  /** The directory sink paths resolve against, found per request from the call's `_meta`. */
  project: (call: { meta?: unknown }) => Promise<Result<string>>
  /**
   * What the environment settles about where this process runs. Where it cannot tell, the
   * agent's \`sandbox\` decides, per request.
   */
  where?: Whereabouts
  /** How the host introduced itself at initialize; read per request, since it is unknown at registration. */
  clientInfo?: () => { readonly name: string } | undefined
  /** Runs each call, so the launcher in front of the server knows when it is busy. */
  during?: IdleReport['during']
}) => {
  /** Names only, and only once something was written: an open request has nothing to report. */
  const fileKeysOf = async (request: SecretRequest) =>
    request.status === 'written' ? sinkKeyNames(request.sink) : []

  const fileKeysReport = (fileKeys: readonly string[]) => (fileKeys.length === 0 ? {} : { file_keys: fileKeys })

  const emojiReport = (request: SecretRequest) => (request.emoji === undefined ? {} : { emoji: request.emoji })

  /**
   * The line to say, first in the result: Claude Code hands the model, and draws under the call,
   * the structured result alone, so what comes first there is what is read and seen first.
   */
  const tellUser = (request: SecretRequest) =>
    request.status === 'written' && request.emoji !== undefined ? { tell_user: `Fingerprint ${request.emoji}` } : {}

  const report = async (request: SecretRequest) => {
    const fileKeys = await fileKeysOf(request)
    return bothWays({
      payload: {
        ...tellUser(request),
        request_id: request.id,
        status: request.status,
        names: namesOf(request),
        ...keptReport(request),
        ...emojiReport(request),
        ...fileKeysReport(fileKeys),
        sink: sinkReport(request),
        note: statusNote({ request, fileKeys }),
      },
      lead: headline(request),
    })
  }

  /** What collect_secret answers with, whichever way the request was settled. */
  const answer = async ({ request, presentation }: { request: SecretRequest; presentation?: Presentation }) => {
    const fileKeys = await fileKeysOf(request)
    const relayed =
      presentation?.channel === 'result' || presentation?.channel === 'remote' ? presentation : undefined
    // A tunnel link the host's own dialog is showing stays out of the result.
    const shown = relayed?.channel === 'remote' && relayed.via === 'tunnel' && relayed.shownByHost
    return bothWays({
      payload: {
        ...tellUser(request),
        request_id: request.id,
        status: request.status,
        expires_in: store.expiresInSeconds(request),
        names: namesOf(request),
        ...keptReport(request),
        ...emojiReport(request),
        ...fileKeysReport(fileKeys),
        sink: sinkReport(request),
        note: relayed === undefined ? statusNote({ request, fileKeys }) : noteFor(relayed),
        ...(relayed === undefined || shown ? {} : { url: relayed.url }),
      },
      lead: headline(request),
    })
  }

  /**
   * A request of generated keys alone has nothing for the human to type, so it is written
   * at once. A git-tracked destination is refused, because the override is the human's
   * to give, on the page.
   */
  const writeAtOnce = async ({
    secrets,
    sink,
    reason,
  }: {
    secrets: readonly RequestedSecret[]
    sink: ResolvedSink
    reason: string
  }): Promise<Result<SecretRequest>> => {
    if (sink.tracked) {
      return fail(
        `git tracks ${sink.relativePath}, and only the human can allow a write there. Use a file git ignores, or ask for the generated keys together with one the human types, so the page can offer the override.`,
      )
    }
    const request = store.create({ secrets, reason, sink })
    const values = valuesToWrite({ secrets, typed: new Map() })
    const written = values.length === 0 ? ok(sink) : await writeToSink({ sink, values, allowTracked: false })
    if (!written.ok) {
      store.expire(request.id)
      return written
    }
    return ok(store.markWritten(request.id) ?? request)
  }

  const missing = (requestId: string) => ({
    isError: true,
    content: [
      {
        type: 'text' as const,
        text: `No offprompt request with id ${requestId}. It may have expired with the server restart.`,
      },
    ],
  })

  server.registerTool(
    'collect_secret',
    {
      title: 'Collect a secret from the human',
      description: COLLECT_DESCRIPTION,
      inputSchema: collectInput,
      outputSchema: collectOutput,
      annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
    },
    async (input, extra) => during(async () => {
      const refused = (message: string) => ({
        isError: true,
        content: [{ type: 'text' as const, text: `offprompt refused that request: ${message}` }],
      })

      const root = await project({ meta: extra._meta })
      if (!root.ok) return refused(root.message)
      const sink = await resolveSink({ root: root.value, spec: input.sink })
      if (!sink.ok) return refused(sink.message)
      if (sink.value.kind === 'file' && input.secrets.length > 1) {
        return refused('a file sink holds exactly one value; use a dotenv sink for several')
      }
      const duplicate = input.secrets.find(
        (secret, index) => input.secrets.findIndex(other => other.name === secret.name) !== index,
      )
      if (duplicate !== undefined) return refused(`${duplicate.name} is asked for twice`)

      const requested = await requestedSecrets({ sink: sink.value, asks: input.secrets })
      if (!requested.ok) return refused(requested.message)
      const secrets = requested.value

      if (secrets.every(secret => secret.value.kind === 'generated')) {
        const written = await writeAtOnce({ secrets, sink: sink.value, reason: input.reason })
        return written.ok ? answer({ request: written.value }) : refused(written.message)
      }

      // From a sandbox the values cross a tunnel or a vendor's forwarding, so the page seals
      // them to a key pair made for this request alone.
      const sandboxed = where === 'remote' || (where === 'unsure' && input.sandbox === true)
      const pair = sandboxed ? await newSealPair() : undefined
      const asker = askerFor({ clientInfo: clientInfo() })
      const request = store.create({
        secrets,
        reason: input.reason,
        sink: sink.value,
        ...(pair === undefined ? {} : { sealKey: pair.sealKey }),
        ...(asker === undefined ? {} : { asker }),
      })
      const presentation = await present({
        request,
        url: loopback.urlFor(request),
        ...(pair === undefined ? {} : { remote: { path: `/r/${request.token}`, publicKey: pair.publicKey } }),
      })

      // The call waits for the human, except where the model has to relay the URL itself:
      // blocking there would hold back the one message that gets them to the page. A remote
      // request never waits either, since it outlives any one call. Both poll with await_secret.
      const settled =
        presentation.channel === 'result' || presentation.channel === 'remote'
          ? request
          : (await store.waitFor(request.id, store.ttlMs + WAIT_SLACK_MS)) ?? request

      return answer({ request: settled, presentation })
    }),
  )

  server.registerTool(
    'await_secret',
    {
      title: 'Wait for a secret to be written',
      description: AWAIT_DESCRIPTION,
      inputSchema: awaitInput,
      outputSchema: statusOutput,
      annotations: { readOnlyHint: true, openWorldHint: false },
    },
    async input =>
      during(async () => {
        const settled = await store.waitFor(input.request_id, AWAIT_TIMEOUT_MS)
        if (settled === undefined) return missing(input.request_id)
        return report(settled)
      }),
  )

  server.registerTool(
    'cancel_secret',
    {
      title: 'Cancel a secret request',
      description: CANCEL_DESCRIPTION,
      inputSchema: awaitInput,
      outputSchema: statusOutput,
      annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
    },
    async input =>
      during(async () => {
        const closed = store.expire(input.request_id)
        if (closed === undefined) return missing(input.request_id)
        return report(closed)
      }),
  )
}
